spring.application.name=online_course


























































spring.datasource.url=jdbc:postgresql://localhost:5432/Online_Course_System
spring.datasource.username=postgres
spring.datasource.password=124578

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
